print("Biodata Mahasiswa Unama Jambi  : ")
print("=============================  : ")
print("")
input("NIM  : ")
input("NAMA MAHASISWA  : ")
input("JENIS KEALAMIN  : ")
input("ALAMAT          : ")
input("NO HANDPHONE    : ")
input("CITA CITA       : ")
input("HOBI            : ")